KenkoriaCity_MapScripts::
	.byte 0

KenkoriaCity_EventScript_BikeShopSign::
	msgbox KenkoriaCity_Text_BikeShopSign, MSGBOX_SIGN
	end

KenkoriaCity_EventScript_GymSign::
	msgbox KenkoriaCity_Text_GymSign, MSGBOX_SIGN
	end

KenkoriaCity_EventScript_CitySign::
	msgbox KenkoriaCity_Text_CitySign, MSGBOX_SIGN
	end

KenkoriaCity_EventScript_BikeGirl::
	msgbox KenkoriaCity_Text_BikeGirl, MSGBOX_NPC
	end

KenkoriaCity_EventScript_BikeBoy::
	msgbox KenkoriaCity_Text_BikeBoy, MSGBOX_NPC
	end

KenkoriaCity_EventScript_Elder::
	msgbox KenkoriaCity_Text_Elder, MSGBOX_NPC
	end

KenkoriaCity_EventScript_Zigzagoon::
	msgbox KenkoriaCity_Text_Zigzagoon, MSGBOX_NPC
	end

KenkoriaCity_EventScript_Beauty::
	msgbox KenkoriaCity_Text_Beauty, MSGBOX_NPC
	end

KenkoriaCity_Text_BikeShopSign:
	.string "KENKORIA CITY Bike Shop\n"
	.string "“Get your new shiny bicycle today!”$"

KenkoriaCity_Text_GymSign:
	.string "KENKORIA CITY Gym\n"
	.string "“Bring your Wailmer Pail with you.”$"

KenkoriaCity_Text_CitySign:
	.string "KENKORIA CITY\n"
	.string "A city on the WEST of KENKORIA SEA.$"

KenkoriaCity_Text_BikeGirl:
	.string "Welcome to KENKORIA CITY!\n"
	.string "In here you can obtain a bicycle.$"

KenkoriaCity_Text_BikeBoy:
	.string "KENKORIA CITY has a lot to offer in\n"
	.string "terms of supplies.\p"
	.string "You should stack on some items from\n"
	.string "the mart.$"

KenkoriaCity_Text_Elder:
	.string "I like to come sit here and watch the sea\n"
	.string "from the bench.\p"
	.string "It's nice to relax and take it easy from\n"
	.string "time to time.$"

KenkoriaCity_Text_Zigzagoon:
	.string "Zig zig$"

KenkoriaCity_Text_Beauty:
	.string "KENKORIA CITY Gym has a lot of women in it.\p"
	.string "They are all there to make sure the\n"
	.string "flowers grow as beautiful as they can be.\p"
	.string "We are looking for CELEBI to visit so that\n"
	.string "the plants will flourish.$"
