gText_Birch_Welcome::
	.string "Hi! You are dreaming of my forthcoming!\p"
	.string "I'm coming to you to give you a POKéMON!\p"
	.string "My name is ARACUARIA.\p"
	.string "But everyone calls me ARIA, the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Inorder to survive in this world\n"
	.string "you'd need creatures known as POKéMON.\p"
	.string "We humans strive using POKéMON,\n"
	.string "at times of peace and conflict, \l"
	.string "at times of research and discovery.\p"
	.string "And sometimes, we work together\n"
	.string "and discover new possibilies.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "I study the pseudo-legendary POKéMON.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's dreaming\n"
	.string "right now.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be seeing you later.\n"
	.string "I will come to you.\p"
	.string "$"
