HawamCity_RivalsHouse_MapScripts::
	.byte 0

HawamCity_RivalsHouse_EventScript_Sis::
	msgbox HawamCity_RivalsHouse_MissingSis, MSGBOX_NPC
	end

HawamCity_RivalsHouse_MissingSis:
	.string "My sis? Noa?\n"
	.string "She has been on her adventure for\l"
	.string "quite some time now.\p"
	.string "I hope she stays safe out there.\n"
	.string "There are many dangerous people who\l"
	.string "want to take advantage of you.$"
