Common_EventScript_SetGymTrainers::
	switch VAR_0x8008
	case 1, PtolemaisCity_Gym_SetGymTrainers
	case 2, KerenCity_Gym_SetGymTrainers
	case 3, KenkoriaCity_Gym_SetGymTrainers
	case 4, PinpointCity_Gym_SetGymTrainers
	case 5, HawamCity_Gym_SetGymTrainers
	case 6, HaruTelCity_Gym_SetGymTrainers
	case 7, JebusCity_Gym_SetGymTrainers
	case 8, SheshBeshCity_Gym_SetGymTrainers
	end

PtolemaisCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_ANDREA
	settrainerflag TRAINER_CRISSY
	settrainerflag TRAINER_BRIANNA
	settrainerflag TRAINER_CONNIE
	settrainerflag TRAINER_BRIDGET
	settrainerflag TRAINER_OLIVIA
	settrainerflag TRAINER_TIFFANY
	settrainerflag TRAINER_BETHANY
	settrainerflag TRAINER_ANNIKA
	settrainerflag TRAINER_DAPHNE
	return

KerenCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_JOHNSON
	settrainerflag TRAINER_WYATT
	settrainerflag TRAINER_MARC
	settrainerflag TRAINER_LILITH
	settrainerflag TRAINER_CRISTIAN
	settrainerflag TRAINER_BRENDEN
	settrainerflag TRAINER_LAURA
	settrainerflag TRAINER_JOCELYN
	settrainerflag TRAINER_RHETT
	return

KenkoriaCity_Gym_SetGymTrainers::
	settrainerflag TRAINER_DAISY
	settrainerflag TRAINER_MELISSA
	settrainerflag TRAINER_BROOKE_1
	settrainerflag TRAINER_CINDY_1
	settrainerflag TRAINER_RACHEL
	settrainerflag TRAINER_ROSE_1
	settrainerflag TRAINER_VICTORIA
	settrainerflag TRAINER_VICKY
	settrainerflag TRAINER_CELIA
	settrainerflag TRAINER_LYDIA_2
	settrainerflag TRAINER_CELINA
	settrainerflag TRAINER_CINDY_2
	return

PinpointCity_Gym_SetGymTrainers::
	return

HawamCity_Gym_SetGymTrainers::
	return

HaruTelCity_Gym_SetGymTrainers::
	return

JebusCity_Gym_SetGymTrainers::
	return

SheshBeshCity_Gym_SetGymTrainers::
	return
