PtolemaisCity_Gym_B1F_MapScripts::
	.byte 0

PtolemaisCity_Gym_B1F_EventScript_Yael::
	trainerbattle_single TRAINER_ANDREA, PtolemaisCity_Gym_B1F_Text_YaelIntro, PtolemaisCity_Gym_B1F_Text_YaelDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_YaelPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Reut::
	trainerbattle_single TRAINER_CRISSY, PtolemaisCity_Gym_B1F_Text_ReutIntro, PtolemaisCity_Gym_B1F_Text_ReutDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_ReutPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Ofek::
	trainerbattle_single TRAINER_BRIANNA, PtolemaisCity_Gym_B1F_Text_OfekIntro, PtolemaisCity_Gym_B1F_Text_OfekDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_OfekPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Lior::
	trainerbattle_single TRAINER_CONNIE, PtolemaisCity_Gym_B1F_Text_LiorIntro, PtolemaisCity_Gym_B1F_Text_LiorDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_LiorPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Ziv::
	trainerbattle_single TRAINER_BRIDGET, PtolemaisCity_Gym_B1F_Text_ZivIntro, PtolemaisCity_Gym_B1F_Text_ZivDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_ZivPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Tamar::
	trainerbattle_single TRAINER_OLIVIA, PtolemaisCity_Gym_B1F_Text_TamarIntro, PtolemaisCity_Gym_B1F_Text_TamarDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_TamarPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Neta::
	trainerbattle_single TRAINER_TIFFANY, PtolemaisCity_Gym_B1F_Text_NetaIntro, PtolemaisCity_Gym_B1F_Text_NetaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_NetaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Ilana::
	trainerbattle_single TRAINER_BETHANY, PtolemaisCity_Gym_B1F_Text_IlanaIntro, PtolemaisCity_Gym_B1F_Text_IlanaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_IlanaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Yarden::
	trainerbattle_single TRAINER_ANNIKA, PtolemaisCity_Gym_B1F_Text_YardenIntro, PtolemaisCity_Gym_B1F_Text_YardenDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_YardenPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Mia::
	trainerbattle_single TRAINER_DAPHNE, PtolemaisCity_Gym_B1F_Text_MiaIntro, PtolemaisCity_Gym_B1F_Text_MiaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_MiaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_Text_YaelIntro:
	.string "I love puzzles, that's why I decided\n"
	.string "to help run this icy challenge!$"

PtolemaisCity_Gym_B1F_Text_YaelDefeat:
	.string "Ugh, you got the best of me.$"

PtolemaisCity_Gym_B1F_Text_YaelPostBattle:
	.string "Watch what happens if you crack all\n"
	.string "the floor tiles.$"

PtolemaisCity_Gym_B1F_Text_ReutIntro:
	.string "You came all the way here, but you won't\n"
	.string "get to see IDO.\p"
	.string "Not if you lose to me, you won't!$"

PtolemaisCity_Gym_B1F_Text_ReutDefeat:
	.string "You're strong!\n"
	.string "I was fooled by your cute looks!$"

PtolemaisCity_Gym_B1F_Text_ReutPostBattle:
	.string "You might be good enough to avoid\n"
	.string "being wiped out in one swing by IDO.$"

PtolemaisCity_Gym_B1F_Text_OfekIntro:
	.string "There is something very calming\n"
	.string "in water…\p"
	.string "The very beauty of it compelled me to\n"
	.string "become a TRAINER.$"

PtolemaisCity_Gym_B1F_Text_OfekDefeat:
	.string "You battled with more beauty than\n"
	.string "I could show you…$"

PtolemaisCity_Gym_B1F_Text_OfekPostBattle:
	.string "The grace you bring to battle is\n"
	.string "fabulous.\p"
	.string "Oh… I'm so glad to have found\n"
	.string "WATER POKéMON.$"

PtolemaisCity_Gym_B1F_Text_LiorIntro:
	.string "I should teach you how harsh battles\n"
	.string "can be.$"

PtolemaisCity_Gym_B1F_Text_LiorDefeat:
	.string "Oh.\n"
	.string "You're strong.$"

PtolemaisCity_Gym_B1F_Text_LiorPostBattle:
	.string "I'll tell you something good.\p"
	.string "If you want to reach IDO, you\n"
	.string "need to walk on each floor tile once.$"

PtolemaisCity_Gym_B1F_Text_ZivIntro:
	.string "I love to see the world and \n"
	.string "go outside…\p"
	.string "I wish the gym leader did the same.$"

PtolemaisCity_Gym_B1F_Text_ZivDefeat:
	.string "What a nice potential you have!$"

PtolemaisCity_Gym_B1F_Text_ZivPostBattle:
	.string "Go explore the world, I imagine\n"
	.string "training in all kinds of other\l"
	.string "places will make you stronger.\l"
	.string "But above all, it looks more fun.$"

PtolemaisCity_Gym_B1F_Text_TamarIntro:
	.string "I train my POKéMON together with\n"
	.string "IDO.\p"
	.string "Don't think I'm a pushover.$"

PtolemaisCity_Gym_B1F_Text_TamarDefeat:
	.string "I was beaten…$"

PtolemaisCity_Gym_B1F_Text_TamarPostBattle:
	.string "I think you have potential.\n"
	.string "Why don't you stay and train with us?$"

PtolemaisCity_Gym_B1F_Text_NetaIntro:
	.string "A graceful glide across the ice while\n"
	.string "crossing no lines…\p"
	.string "A TRAINER putting on that performance\n"
	.string "would be elegantly beautiful!$"

PtolemaisCity_Gym_B1F_Text_NetaDefeat:
	.string "Well, excuse me?!$"

PtolemaisCity_Gym_B1F_Text_NetaPostBattle:
	.string "This is really obvious, but how strong\n"
	.string "you are as a TRAINER has nothing to do\l"
	.string "with how young or old you are.$"

PtolemaisCity_Gym_B1F_Text_IlanaIntro:
	.string "You look kinda interested but not\n"
	.string "really. All of me is not for you.$"

PtolemaisCity_Gym_B1F_Text_IlanaDefeat:
	.string "My eyes are up here!$"

PtolemaisCity_Gym_B1F_Text_IlanaPostBattle:
	.string "I wish I could forget about our\n"
	.string "encounter. I was not interested.$"

PtolemaisCity_Gym_B1F_Text_YardenIntro:
	.string "Bring me more rare WATER POKéMON.\n"
	.string "I love all of them.$"

PtolemaisCity_Gym_B1F_Text_YardenDefeat:
	.string "Oh, there now! Did you have a good look\n"
	.string "at my POKéMON?$"

PtolemaisCity_Gym_B1F_Text_YardenPostBattle:
	.string "This gym has so many WATER type\n"
	.string "POKéMON.\p"
	.string "I'm so glad to be here to enjoy\n"
	.string "them…$"

PtolemaisCity_Gym_B1F_Text_MiaIntro:
	.string "Giggle…\n"
	.string "Your grim look is so charming.$"

PtolemaisCity_Gym_B1F_Text_MiaDefeat:
	.string "Oh, dear.\n"
	.string "I went much too easy on you.$"

PtolemaisCity_Gym_B1F_Text_MiaPostBattle:
	.string "You couldn't lay a finger on me,\n"
	.string "I'm sure. Giggle…$"

