PtolemaisCity_Gym_B1F_MapScripts::
	.byte 0

PtolemaisCity_Gym_B1F_EventScript_Andrea::
	trainerbattle_single TRAINER_ANDREA, PtolemaisCity_Gym_B1F_Text_AndreaIntro, PtolemaisCity_Gym_B1F_Text_AndreaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_AndreaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Crissy::
	trainerbattle_single TRAINER_CRISSY, PtolemaisCity_Gym_B1F_Text_CrissyIntro, PtolemaisCity_Gym_B1F_Text_CrissyDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_CrissyPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Brianna::
	trainerbattle_single TRAINER_BRIANNA, PtolemaisCity_Gym_B1F_Text_BriannaIntro, PtolemaisCity_Gym_B1F_Text_BriannaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_BriannaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Connie::
	trainerbattle_single TRAINER_CONNIE, PtolemaisCity_Gym_B1F_Text_ConnieIntro, PtolemaisCity_Gym_B1F_Text_ConnieDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_ConniePostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Bridget::
	trainerbattle_single TRAINER_BRIDGET, PtolemaisCity_Gym_B1F_Text_BridgetIntro, PtolemaisCity_Gym_B1F_Text_BridgetDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_BridgetPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Olivia::
	trainerbattle_single TRAINER_OLIVIA, PtolemaisCity_Gym_B1F_Text_OliviaIntro, PtolemaisCity_Gym_B1F_Text_OliviaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_OliviaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Tiffany::
	trainerbattle_single TRAINER_TIFFANY, PtolemaisCity_Gym_B1F_Text_TiffanyIntro, PtolemaisCity_Gym_B1F_Text_TiffanyDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_TiffanyPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Bethany::
	trainerbattle_single TRAINER_BETHANY, PtolemaisCity_Gym_B1F_Text_BethanyIntro, PtolemaisCity_Gym_B1F_Text_BethanyDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_BethanyPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Annika::
	trainerbattle_single TRAINER_ANNIKA, PtolemaisCity_Gym_B1F_Text_AnnikaIntro, PtolemaisCity_Gym_B1F_Text_AnnikaDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_AnnikaPostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_EventScript_Daphne::
	trainerbattle_single TRAINER_DAPHNE, PtolemaisCity_Gym_B1F_Text_DaphneIntro, PtolemaisCity_Gym_B1F_Text_DaphneDefeat
	msgbox PtolemaisCity_Gym_B1F_Text_DaphnePostBattle, MSGBOX_AUTOCLOSE
	end

PtolemaisCity_Gym_B1F_Text_AndreaIntro:
	.string "I'll show you the sublime techniques\n"
	.string "I learned from our LEADER JUAN!$"

PtolemaisCity_Gym_B1F_Text_AndreaDefeat:
	.string "Please forgive me, JUAN…$"

PtolemaisCity_Gym_B1F_Text_AndreaPostBattle:
	.string "Watch what happens if you crack all\n"
	.string "the floor tiles.$"

PtolemaisCity_Gym_B1F_Text_CrissyIntro:
	.string "You came all the way here, but you won't\n"
	.string "get to see JUAN.\p"
	.string "Not if you lose to me, you won't!$"

PtolemaisCity_Gym_B1F_Text_CrissyDefeat:
	.string "You're strong!\n"
	.string "I was fooled by your cute looks!$"

PtolemaisCity_Gym_B1F_Text_CrissyPostBattle:
	.string "You might be good enough to avoid\n"
	.string "being wiped out in one hit by JUAN.$"

PtolemaisCity_Gym_B1F_Text_DaphneIntro:
	.string "The sight of JUAN conducting\n"
	.string "a battle…\p"
	.string "The very beauty of it compelled me to\n"
	.string "become a TRAINER.$"

PtolemaisCity_Gym_B1F_Text_DaphneDefeat:
	.string "You battled with more beauty than\n"
	.string "I could muster…$"

PtolemaisCity_Gym_B1F_Text_DaphnePostBattle:
	.string "The grace you bring to battle is\n"
	.string "fabulous.\p"
	.string "Oh… I'm so fortunate to have found\n"
	.string "POKéMON.$"

PtolemaisCity_Gym_B1F_Text_ConnieIntro:
	.string "I should teach you how harsh battles\n"
	.string "can be.$"

PtolemaisCity_Gym_B1F_Text_ConnieDefeat:
	.string "Oh.\n"
	.string "You're strong.$"

PtolemaisCity_Gym_B1F_Text_ConniePostBattle:
	.string "I'll tell you something good.\p"
	.string "If you want to reach JUAN, you\n"
	.string "need to walk on each floor tile once.$"

PtolemaisCity_Gym_B1F_Text_BridgetIntro:
	.string "The POKéMON GYM of the highest level\n"
	.string "in the HOENN region…\p"
	.string "That's the SOOTOPOLIS GYM.$"

PtolemaisCity_Gym_B1F_Text_BridgetDefeat:
	.string "What a high level you are!$"

PtolemaisCity_Gym_B1F_Text_BridgetPostBattle:
	.string "Rather than being satisfied by being\n"
	.string "in a strong GYM, I imagine training in\l"
	.string "other places will make you stronger.\l"
	.string "But above all, it looks more fun.$"

PtolemaisCity_Gym_B1F_Text_OliviaIntro:
	.string "I train my POKéMON together with\n"
	.string "JUAN.\p"
	.string "Don't think I'm a pushover.$"

PtolemaisCity_Gym_B1F_Text_OliviaDefeat:
	.string "I was beaten…$"

PtolemaisCity_Gym_B1F_Text_OliviaPostBattle:
	.string "I think you have potential.\n"
	.string "Why don't you stay and train with us?$"

PtolemaisCity_Gym_B1F_Text_TiffanyIntro:
	.string "A graceful glide across the ice while\n"
	.string "crossing no lines…\p"
	.string "A TRAINER putting on that performance\n"
	.string "would be elegantly beautiful!$"

PtolemaisCity_Gym_B1F_Text_TiffanyDefeat:
	.string "Well, excuse me?!$"

PtolemaisCity_Gym_B1F_Text_TiffanyPostBattle:
	.string "This is really obvious, but how strong\n"
	.string "you are as a TRAINER has nothing to do\l"
	.string "with how young or old you are.$"

PtolemaisCity_Gym_B1F_Text_BethanyIntro:
	.string "When I'm with my POKéMON, the time\n"
	.string "flies by before you can say, “Oops!”$"

PtolemaisCity_Gym_B1F_Text_BethanyDefeat:
	.string "Oops!$"

PtolemaisCity_Gym_B1F_Text_BethanyPostBattle:
	.string "I wish I could forget about lost causes\n"
	.string "before I can manage an “Oops!”$"

PtolemaisCity_Gym_B1F_Text_AnnikaIntro:
	.string "I can battle with really rare POKéMON\n"
	.string "if you'd like.$"

PtolemaisCity_Gym_B1F_Text_AnnikaDefeat:
	.string "Oh, there now! Did you have a good look\n"
	.string "at my POKéMON?$"

PtolemaisCity_Gym_B1F_Text_AnnikaPostBattle:
	.string "I came to this GYM because JUAN\n"
	.string "praised me for my darling POKéMON.\p"
	.string "Oh, if only I'd met JUAN years ago\n"
	.string "when I was younger…$"

PtolemaisCity_Gym_B1F_Text_BriannaIntro:
	.string "Giggle…\n"
	.string "Your grim look is so charming.$"

PtolemaisCity_Gym_B1F_Text_BriannaDefeat:
	.string "Oh, dear.\n"
	.string "I went much too easy on you.$"

PtolemaisCity_Gym_B1F_Text_BriannaPostBattle:
	.string "You couldn't lay a finger on JUAN,\n"
	.string "I'm sure. Giggle…$"

